<div class="mobile-nav visible-sm visible-xs">
    <div class="dashboard">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-2">
                    <div class="table trigger-mobile">
                        <div class="cell">
                            <a href="#">
                                <span>Menu</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-5">
                    <div class="table logo">
                        <div class="cell">
                            <a href="/index.html">
                                <img src="static/images/convatec_logo_rgb_primary_white-crop.png?anchor=center&amp;mode=crop&amp;height=50&amp;rnd=131200595130000000">
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-3">
                    <div class="table">
                        <div class="cell">
                            <a href="https://www.convatec.com/choose-your-country/" target="_blank">
                                <span class="glyphicon  glyphicon-globe" style="margin-left:10px;font-size:25px;"></span>
                            </a>
                        </div>
                        <div id="mobileSearchGlyphDiv" class="cell">
                            <a href="#">
                                <span class="glyphicon glyphicon-search" style="margin-left:10px;font-size:25px;"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav id="mobileSearchPanelDiv" style="margin-top: 60px;">
        <ul class="tier-1">
            <li class="active">
                <a href="#">Search</a>
                <div class="tier-2">
                    <ul class="small">
                        <li>
                            <form id="global-search-mobile" action="https://www.convatec.com/forms/search">
                                <input class="form-control floating-label" name="q" type="text" placeholder="Search" />
                                <button type="submit" class="btn pull-right">
                                    <i class="ion-android-search"></i>
                                </button>
                            </form>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
    <nav id="mobileMenuNav" style="margin-top: 60px;">
        <ul class="tier-1">
            <li class="active">
                <a href="#">About Us</a>
                <div class="tier-2">
                    <h3 class="border">
                        <a href="/about-us.html">
                            About Us
                            <i class="icon ion-chevron-right"></i>
                        </a>
                    </h3>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Our Purpose and Values
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Boards of Directors
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Our History
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Company Leadership
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Locations
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/about-us-purpose.html">
                                    Awards and Recognitions
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">Our Franchises</a>
                <div class="tier-2">
                    <h3 class="border">
                        <a href="/our-franchises.html">
                            Our Franchises
                            <i class="icon ion-chevron-right"></i>
                        </a>
                    </h3>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/our-franchises-wound-care.html">
                                    Advanced Wound Care
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/our-franchises-continence-care.html">
                                    Continence & Critical Care
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/our-franchises-ostomy-care.html">
                                    Ostomy Care
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/our-franchises-infusion-devices.html">
                                    Infusion Devices
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">Investors</a>
                <div class="tier-2">
                    <h3 class="border">
                        <a href="/investors-landing.html">
                            Investors
                            <i class="icon ion-chevron-right"></i>
                        </a>
                    </h3>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="/investors-reasons-to-invest.html">
                                    Reasons to Invest
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-results-page.html">
                                    Results, Reports and Presentations
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-rns-filings.html">
                                    RNS &amp; Filings
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-analyst-coverage.html">
                                    Analyst Coverage
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-governance-structure.html">
                                    Corporate Governance
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-shareholder-services.html">
                                    Shareholder Services
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-share-calculator.html">
                                    Share Price and Tools
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <h4 class="border">
                                <a href="/investors-contacts.html">
                                    Investor Contacts
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">Corporate Social Responsibility</a>
                <div class="tier-2">
                    <h3 class="border">
                        <a href="https://www.convatec.com/products/">
                            Corporate Social Responsibility
                            <i class="icon ion-chevron-right"></i>
                        </a>
                    </h3>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Quality Policy
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Code Ethics and Business Conduct
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Grants and Contributions
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Commitment to EHS
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Marketing Compliance
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Supplier Diversity
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="#">Media</a>
                <div class="tier-2">
                    <h3 class="border">
                        <a href="https://www.convatec.com/products/">
                            Media
                            <i class="icon ion-chevron-right"></i>
                        </a>
                    </h3>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Press Releases



                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                2016
                            </a>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Fact Sheet
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Media Library
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                    <ul class="small">
                        <li>
                            <h4 class="border">
                                <a href="https://www.convatec.com/products/ostomy">
                                    Media Contacts
                                    <i class="icon ion-chevron-right"></i>
                                </a>
                            </h4>
                        </li>
                    </ul>
                </div>
            </li>
            <li>
                <a href="https://www.convatec.com/contact-us/">Contact Us</a>
            </li>
        </ul>
    </nav>
    <div class="mobile-overlay"></div>
</div>
<div class="hidden-xs hidden-sm" id="dashboard">
    <div class="container">
        <div class="row">
            <div class="col-md-3 hidden-sm hidden-xs">
                <a href="index.html">
                    <img src="static/images/convatec-logo-2x.png?anchor=center&amp;mode=crop&amp;height=49&amp;rnd=131200595130000000" alt="USA Home (US)">
                </a>
            </div>
            <div class="col-md-7 col-xs-12 links">
                <div class="table">
                    <div class="cell">
                        <a href="https://www.convatec.com/choose-your-country/" target="_blank">Select country</a>
                    </div>
                    <div class="cell">
                        <form id="global-search" action="https://www.convatec.com/forms/search">
                            <input class="form-control floating-label" name="q" type="text" placeholder="Search" />
                            <button type="submit" class="btn">
                                <i class="ion-android-search"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="hidden-xs hidden-sm top">
    <div class="background"></div>
    <div class="desktop-menu">
        <div class="navShadow"></div>
        <ul class="tier-1 container">
            <li>
                <div class="table">
                    <div class="cell">
                        <a href="/about-us">About Us</a>
                    </div>
                </div>
                <div class="tier-2">

                    <div class="row">
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Our Purpose and Values
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Boards of Directors
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Our History
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Company Leadership 
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Locations 
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Awards and Recognitions 
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <a href="https://www.convatec.com/continence-critical-care/" style="display:block" target="">
                                <div class="cta" style="background-image: url(static/images/about-lead.jpg);">
                                    <div class="table">
                                        <div class="cell">
                                            <div class="background"></div>
                                            <div class="copy">
                                                <h3>
                                                    <span>About Us</span>
                                                </h3>
                                                <h4></h4>
                                                <span class="ctalink">View All About Us <i class="icon ion-chevron-right"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    
                </div>
            </li>
            <li>
                <div class="table">
                    <div class="cell">
                        <a href="/our-franchises">Our Franchises</a>
                    </div>
                </div>
                <div class="tier-2">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/fecal-incontinence/">
                                            Advanced Wound Care
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/continence-care/">
                                            Continence & Critical Care
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Ostomy Care
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/education-support/">
                                            Infusion Devices
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <a href="https://www.convatec.com/continence-critical-care/" style="display:block" target="">
                                <div class="cta" style="background-image: url(static/images/franchise-lead.jpg);">
                                    <div class="table">
                                        <div class="cell">
                                            <div class="background"></div>
                                            <div class="copy">
                                                <h3>
                                                    <span>Our Franchises</span>
                                                </h3>
                                                <h4></h4>
                                                <span class="ctalink">View All Our Franchises <i class="icon ion-chevron-right"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="table">
                    <div class="cell">
                        <a href="/investors-landing.html">Investors</a>
                    </div>
                </div>
                <div class="tier-2">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-reasons-to-invest.html">
                                            Reasons to Invest
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-results-page.html">
                                            Results, Reports and Presentations
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-rns-filings.html">
                                            RNS &amp; Filings
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-analyst-coverage.html">
                                            Analyst Coverage
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-governance-structure.html">
                                            Corporate Governance
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-shareholder-services.html">
                                            Shareholder Services
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-share-calculator.html">
                                            Share Price and Tools
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                                <li>
                                    <h4 class="border">
                                        <a href="/investors-contacts.html">
                                            Investor Contacts
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <a href="/investors-landing.html" style="display:block" target="">
                                <div class="cta" style="background-image: url(static/images/investors-lead.jpg);">
                                    <div class="table">
                                        <div class="cell">
                                            <div class="background"></div>
                                            <div class="copy">
                                                <h3>
                                                    <span>Investors</span>
                                                </h3>
                                                <h4></h4>
                                                <span class="ctalink">View All Investors <i class="icon ion-chevron-right"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="table">
                    <div class="cell">
                        <a href="/corporate-responsibility">Corporate Social Reponsibility</a>
                    </div>
                </div>
                <div class="tier-2">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Quality Policy
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Code Ethics and Business Conduct
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="#">
                                            Grants and Contributions
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Commitment to EHS
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Marketing Compliance 
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Supplier Diversity
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <a href="https://www.convatec.com/continence-critical-care/" style="display:block" target="">
                                <div class="cta" style="background-image: url(static/images/responsibility-lead.jpg);">
                                    <div class="table">
                                        <div class="cell">
                                            <div class="background"></div>
                                            <div class="copy">
                                                <h3>
                                                    <span>Corporate Social Responsibility</span>
                                                </h3>
                                                <h4></h4>
                                                <span class="ctalink">View All Corporate Social Responsibility <i class="icon ion-chevron-right"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    
                </div>
            </li>
            <li>
                <div class="table">
                    <div class="cell">
                        <a href="/media">Media</a>
                    </div>
                </div>
                <div class="tier-2">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/fecal-incontinence/">
                                            Press Releases
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/continence-care/">
                                            Fact Sheet
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="small">
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/iap-monitoring/">
                                            Media Library
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            
                                <li>
                                    <h4 class="border">
                                        <a href="https://www.convatec.com/continence-critical-care/education-support/">
                                            Media Contacts
                                            <i class="icon ion-chevron-right"></i>
                                        </a>
                                    </h4>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <a href="https://www.convatec.com/continence-critical-care/" style="display:block" target="">
                                <div class="cta" style="background-image: url(static/images/media-lead.jpg);">
                                    <div class="table">
                                        <div class="cell">
                                            <div class="background"></div>
                                            <div class="copy">
                                                <h3>
                                                    <span>Media</span>
                                                </h3>
                                                <h4></h4>
                                                <span class="ctalink">View All Media <i class="icon ion-chevron-right"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <li class="menu-meplus">
                <div class="table">
                    <div class="cell">
                        <div class="sharePrice">
                            Share Price: <span>450.50 GBP</span>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>